apiVersion: v1
kind: Service
metadata:
  name: maven-service
spec:
  type: NodePort
  ports:
  - name: renren
    port: 8080
    nodePort: 31002
    targetPort: 8080
    protocol: TCP
  selector:
    app: renren
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maven-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: renren
    spec:
      containers:
        - name: renren
          image: 127.0.0.1:8089/test/renren:latest
          ports:
          - containerPort: 8080
          env:
            - name: key
              value: "value"
